apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accio
  name: accio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accio
  template:
    metadata:
      labels:
        app: accio
    spec:
      containers:
      - image: api-core_api:latest
        name: accio
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
        ports:
        - containerPort: 3000
          name: postgres
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-auth
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-auth
              key: username
        envFrom:
        - configMapRef:
            name: postgres-configmap