apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_PASSWORD
          value: "accio"
        - name: POSTGRES_USER
          value: "accio"
        - name: POSTGRES_DB
          value: "accio"
        - name: PGDATA
          value: "/var/lib/postgresql/data/some_name/"

      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres

  

