apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xdatabaseinstances.aws.accio.io
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: accio.io/v1alpha1
    kind: XDatabaseInstance
  resources:
  - name: rds-instance
    base:
      apiVersion: rds.aws.upbound.io/v1beta1
      kind: Instance
      spec:
        forProvider:
          region: us-east-1
          dbInstanceClass: db.t3.micro
          engine: postgres
          allocatedStorage: 20
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.engine
      toFieldPath: spec.forProvider.engine
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xstoragebuckets.aws.accio.io
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: accio.io/v1alpha1
    kind: XStorageBucket
  resources:
  - name: s3-bucket
    base:
      apiVersion: s3.aws.upbound.io/v1beta1
      kind: Bucket
      spec:
        forProvider:
          region: us-east-1
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
