apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: validator
  name: validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator
  template:
    metadata:
      labels:
        app: validator
    spec:
      containers:
      - image: api-validator_api:latest
        name: validator
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: postgres
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: CORE_API
          value: "accio.default.svc.cluster.local"