apiVersion: v1
kind: Service
metadata:
  labels:
    app: validator
  name: validator
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: validator
  type: ClusterIP
