apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcomputevms.accio.io
spec:
  group: accio.io
  names:
    kind: XComputeVM
    plural: xcomputevms
  claimNames:
    kind: ComputeVM
    plural: computevms
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    type: string
                    description: Cloud provider region
                  instanceType:
                    type: string
                    description: Size of the instance (e.g., t3.micro, small)
                  diskSize:
                    type: integer
                    description: Disk size in GB
                required:
                - region
                - instanceType
            required:
            - parameters
