apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabaseinstances.accio.io
spec:
  group: accio.io
  names:
    kind: XDatabaseInstance
    plural: xdatabaseinstances
  claimNames:
    kind: DatabaseInstance
    plural: databaseinstances
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    type: string
                    description: Cloud provider region
                  engine:
                    type: string
                    description: Database engine (postgres, mysql)
                  version:
                    type: string
                    description: Database version
                  size:
                    type: string
                    description: Database instance size
                required:
                - region
                - engine
                - size
            required:
            - parameters
